apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: test-space
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-ep
  namespace: test-space
subsets:
  - addresses:
      - ip: 172.16.0.15
    ports:
      - port: 3306
