apiVersion: v1
kind: Service
metadata:
  name: es-svc
  namespace: test-space
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: es-svc
  namespace: test-space
subsets:
  - addresses:
      - ip: 172.16.0.32
    ports:
      - port: 9200