apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  namespace: test-space
spec:
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - name: xxl-job-admin
        image: harbor.x.com.cn/system/xxljob/xxl-job-admin:2.2.0
        ports:
        - containerPort: 8080
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://172.16.16.3:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=test --spring.datasource.password=123456 --spring.datasource.driver-class-name=com.mysql.jdbc.Driver --xxl.job.accessToken=0bETi1jIhYo9fsWl"
      imagePullSecrets:
      - name: harbor.x.com.cn
---
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin
  namespace: test-space
  labels:
    app: xxl-job-admin
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: xxl-job-admin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxl-job-admin
  namespace: test-space
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: /xxl-job-admin
spec:
  tls:
  - hosts:
    - xxl-job-test.x.com.cn
    secretName: x.com.cn-tls
  rules:
  - host: xxl-job-test.x.com.cn
    http:
      paths:
      - path: '/'
        backend:
          serviceName: xxl-job-admin
          servicePort: 8080