apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: test-rocketmq-name-service
  namespace: default
#  ownerReferences:
#  - apiVersion: rocketmq.apache.org/v1alpha1
#    blockOwnerDeletion: true
#    controller: true
#    kind: NameService
#    name: test-rocketmq-name-service
#    uid: ed5276e5-5ea9-4c40-aa2d-8944e20d3734
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: name_service
      name_service_cr: test-rocketmq-name-service
  serviceName: "test-rocketmq-namesrv"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: name_service
        name_service_cr: test-rocketmq-name-service
    spec:
      containers:
        - image: apacherocketmq/rocketmq-nameserver:4.5.0-alpine-operator-0.3.0
          imagePullPolicy: Always
          name: name-service
          ports:
            - containerPort: 9876
              name: main
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/logs
              name: namesrv-storage
              subPath: logs
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}