apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  namespace: test-space
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-datalog
  namespace: test-space
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-logs
  namespace: test-space
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc  