apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: test-space
  labels:
    k8s-app: zookeeper-svc
    app: zookeeper-svc
spec:
  ports:
    - port: 2181
      name: "2181"
      protocol: TCP
    - port: 7000
      name: "7000"
      protocol: TCP
  selector:
    app: zookeeper
  type: NodePort