{{- if or (eq true .Values.deplyApp.appConfigMapAsEnv.enabled) (eq true .Values.configMap.enabled)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "myapp.name" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value }}
{{- end }}

{{- end }}

