apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-server
  namespace: test-space
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-sc
