apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: test-space
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-sc"

