# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
 mode: cluster
 storageClass: 
   provisioner: 

mysql:
 annotations: {}
 resources: {}
 nodeSelector: {}
 affinity: {}
 tolerations: {}
 service:
   port: 3306
 rootPassword: root
 database: nacos_db
 user: test
 password: 123456
 image:
   pullPolicy: IfNotPresent
   repository: nacos/nacos-mysql
   tag: 5.7
 classParameters: {}
 persistence:
   enabled: false
   existingClaim: mysql-data
   #existingClaim:
   claim:
     name: mysql-data
     spec:
       accessModes:
         - ReadWriteOnce
       resources:
         requests:
           storage: 5G
       storageClassName: sc-mysql







############################mysql###########################

############################nacos###########################
replicaCount: 3

image:
  repository: nacos/nacos-server
  tag: 1.4.1
  pullPolicy: IfNotPresent

health:
  enabled: true

env:
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
  dbHost: 172.16.16.3

persistence:
  enabled: true
  storageClassName: sc-nacos
  classParameters: {}
  data:
    accessModes: 
    - ReadWriteOnce
    storageClassName: nfs-sc
    resources:
      requests:
        storage: 5Gi
  plugin:
    accessModes: 
    - ReadWriteOnce
    storageClassName: nfs-sc
    resources:
      requests:
        storage: 5Gi
  log:
    accessModes: 
    - ReadWriteOnce
    storageClassName: nfs-sc
    resources:
      requests:
        storage: 5Gi

service:
  type: ClusterIP
#  type: NodePort
  port: 8848
  nodePort: 30000


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20M
#    kubernetes.io/tls-acme: "true"
  hosts:
    - host: nacos-test.x.com.cn
      paths:
        - /
  tls:
    - secretName: x.com.cn-tls
      hosts:
        - nacos-test.x.com.cn

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
     cpu: 500m
     memory: 2Gi
annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}



